#!/usr/bin/env perl
#
# ARDOC - NIghtly COntrol System
# Author Alex Undrus <undrus@bnl.gov>
# 
# ----------------------------------------------------------
# ardoc_progress_informer
# ----------------------------------------------------------
#
use Env;
my $ARDOC_HOME="$ARDOC_HOME";
my $ARDOC_WEBDIR="$ARDOC_WEBDIR";
my $ARDOC_PROJECT_HOME="$ARDOC_PROJECT_HOME";
my $ARDOC_PROJECT_NAME="$ARDOC_PROJECT_NAME";
my $ARDOC_PROJECT_RELNAME="$ARDOC_PROJECT_RELNAME_COPY";
my $ARDOC_PROJECT_RELNUMB="$ARDOC_PROJECT_RELNUMB_COPY";

my $step=0;
my $param=0;
my $suffix="_${ARDOC_PROJECT_RELNUMB}"; 
if ( ${ARDOC_PROJECT_RELNUMB} eq "" ) { $suffix=""; }

if ($#ARGV >= 0) {$step=$ARGV[0];}
if ($#ARGV >= 1) {$param=$ARGV[1];}

my $progress_file="${ARDOC_WORK_AREA}/ardoc_progress_status";
open(WRITEDATA,">$progress_file");
print WRITEDATA "$step";
close(WRITEDATA);

my $outfile_status="${ARDOC_WEBDIR}/status_rel${suffix}.js";
my $outfile_date="${ARDOC_WEBDIR}/date_rel${suffix}.js";

open(WRITEDATA,">$outfile_status");
print WRITEDATA "function status${suffix}()\{return ";
$_=$step;
SWITCH: {
$_ == 0 && do { print WRITEDATA "'nightly started'\}";\
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_oracle_wrapper.sh 3 python $ARDOC_HOME/ardoc_oracle_reljobs.py >> \$genlogdir/ardoc_general.logora 2>&1");\
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access -b -s \"CONFIG\" -p \"$param\" >> \$genlogdir/ardoc_general.logora 2>&1");\
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access -e -s \"CONFIG\" >> \$genlogdir/ardoc_general.logora 2>&1");\
last SWITCH; };
$_ == 1 && do { print WRITEDATA "'configuration in progress'\}";\
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access -e -s \"TOOLINIT\" --nochange >> \$genlogdir/ardoc_general.logora 2>&1");\
last SWITCH; };
$_ == 2 && do { print WRITEDATA "'checkout done'\}";\
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_oracle_wrapper.sh 3 python $ARDOC_HOME/ardoc_oracle_tags.py >> \$genlogdir/ardoc_general.logora 2>&1");\
last SWITCH; };
$_ == 3 && do { print WRITEDATA "'make started'\}";\
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access -e -s \"PROJECTCONF\" >> \$genlogdir/ardoc_general.logora 2>&1");\
last SWITCH; };
$_ == 4 && do { print WRITEDATA "'make done, tests started'\}"; \
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access_test -e -s \"BUILD\" >> \$genlogdir/ardoc_general.logora 2>&1");\
last SWITCH; };
$_ == 44 && do { system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_oracle_wrapper.sh 3 python $ARDOC_HOME/ardoc_oracle_build_results.py --complete >> \$genlogdir/ardoc_build.logora 2>&1");\
last SWITCH; };
$_ == 5 && do { print WRITEDATA "'kit build in progress'\}"; last SWITCH; };
$_ == 6 && do { print WRITEDATA "'rpm build in progress'\}"; last SWITCH; };
$_ == 7 && do { print WRITEDATA "'qa tests done'\}"; last SWITCH; };
$_ == 8 && do { print WRITEDATA "'integrated tests done'\}"; \
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access -e -s \"INT\" >> \$genlogdir/ardoc_general.logora 2>&1");\
last SWITCH; };
$_ == 9 && do { print WRITEDATA "'kv done'\}"; last SWITCH; };
$_ == 10 && do { print WRITEDATA "'done'\}"; \
system("genlogdir=`dirname $ARDOC_LOG`;$ARDOC_HOME/ardoc_db_access -e -s \"ERR\" >> \$genlogdir/ardoc_general.logora 2>&1");\
system("genlogdir=`dirname $ARDOC_TESTLOG`;$ARDOC_HOME/ardoc_oracle_wrapper.sh 3 python $ARDOC_HOME/ardoc_oracle_results.py -c >> \$genlogdir/ardoc_test_final.logora 2>&1");\
last SWITCH; };
print WRITEDATA "'UNAVAILABLE'\}";
}
close(WRITEDATA);




